name: test

on:
  pull_request:

jobs:
  linux:
    strategy:
      fail-fast: false
      matrix:
        builder:
          - 5.2-7:1.15.7-26.1.2-1
        os:
          - ubuntu22.04
    runs-on: ubuntu-22.04

    container: ghcr.io/emqx/emqx-builder/${{ matrix.builder }}-${{ matrix.os }}

    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive
      - name: gitconfig
        run: git config --system --add safe.directory ${PWD}
      - name: test build
        run: make
